// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNutx9h91d0MrRGmsQs0D9__7tsTP_D-Q',
    appId: '1:762725959551:web:73f5d1cfc280773bef7c4a',
    messagingSenderId: '762725959551',
    projectId: 'index-immigrant-index-2025',
    authDomain: 'index-immigrant-index-2025.firebaseapp.com',
    storageBucket: 'index-immigrant-index-2025.firebasestorage.app',
    measurementId: 'G-SXZRBM6ZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOS8ZYTuif2AffVm4_hrPzey-IySlyM_4',
    appId: '1:762725959551:android:752207078ed59aefef7c4a',
    messagingSenderId: '762725959551',
    projectId: 'index-immigrant-index-2025',
    storageBucket: 'index-immigrant-index-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbV2bSCJTnwjNnlV2kIdqDqG4qHPYNYXg',
    appId: '1:762725959551:ios:9703356f57a3ea11ef7c4a',
    messagingSenderId: '762725959551',
    projectId: 'index-immigrant-index-2025',
    storageBucket: 'index-immigrant-index-2025.firebasestorage.app',
  iosBundleId: 'ca.indexcanada.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbV2bSCJTnwjNnlV2kIdqDqG4qHPYNYXg',
    appId: '1:762725959551:ios:9703356f57a3ea11ef7c4a',
    messagingSenderId: '762725959551',
    projectId: 'index-immigrant-index-2025',
    storageBucket: 'index-immigrant-index-2025.firebasestorage.app',
  iosBundleId: 'ca.indexcanada.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNutx9h91d0MrRGmsQs0D9__7tsTP_D-Q',
    appId: '1:762725959551:web:2e8f3e3ded7b23edef7c4a',
    messagingSenderId: '762725959551',
    projectId: 'index-immigrant-index-2025',
    authDomain: 'index-immigrant-index-2025.firebaseapp.com',
    storageBucket: 'index-immigrant-index-2025.firebasestorage.app',
    measurementId: 'G-NGY4721D5J',
  );

}